title: Mobssie Technology warehouse
description: Technology warehouse
author: Mobssie
github: https://github.com/mobssie
about: FrontEnd Developer
disqus_shortname: mobssie-technology-warehouse
google_analytics: UA-119992833-1
avatar_url: /static/img/jurip.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "https://twitter.com/agusmakmun6"
#    - icon: fa-linkedin
#      link: "https://www.linkedin.com/in/summonagus"
#    - icon: fa-stack-exchange
#      link: "#"
#    - icon: fa-github
#      link: "https://github.com/mobssie"

share:
  twitter_username: mobssie1
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/


url: "https://mobssie.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
